AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # DynamoDB Table for Videos Metadata
  DynamoDBTableVideos:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "n11486546-videos-metadata"
      AttributeDefinitions:
        - AttributeName: "qut-username"
          AttributeType: "S"
        - AttributeName: "videoId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "qut-username"
          KeyType: "HASH"  # Partition key
        - AttributeName: "videoId"
          KeyType: "RANGE" # Sort key
      BillingMode: PAY_PER_REQUEST

  # DynamoDB Table for Blogs
  DynamoDBTableBlogs:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "n11486546-blogs"
      AttributeDefinitions:
        - AttributeName: "qut-username"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "qut-username"
          KeyType: "HASH"  # Partition key
        - AttributeName: "id"
          KeyType: "RANGE" # Sort key
      BillingMode: PAY_PER_REQUEST

Outputs:
  DynamoDBTableVideosName:
    Description: "The name of the DynamoDB table for videos metadata"
    Value: !Ref DynamoDBTableVideos

  DynamoDBTableBlogsName:
    Description: "The name of the DynamoDB table for blogs"
    Value: !Ref DynamoDBTableBlogs
