AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with public access blocked.

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: n11486546-cab432-assignment-2  # Ensure the bucket name is globally unique
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: MySecureBucket

Outputs:
  S3BucketName:
    Description: The name of the created S3 bucket
    Value: !Ref MyS3Bucket
