AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a Secret in AWS Secrets Manager

Resources:
  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: n11486546/assignment2/YoutubeAPIKey
      Description: Secret for my application
      SecretString: '{"YOUTUBE_API_KEY":"AIzaSyC9Pr8-amAEpoufNDH4ZeirhT5c7SOgT7U"}'
      Tags:
        - Key: qut-username
          Value: n11486546@qut.edu.au
        - Key: purpose
          Value: assignment


Outputs:
  SecretArn:
    Description: The ARN of the created secret
    Value: !Ref MySecret
